### ISSUE TITLE
Error showing while use in xcode 12.0

### ISSUE THREAD

**Issue by jignesh133** [globulus/swiftui-date-picker-dialog#1]
Function builder attribute 'ViewBuilder' can only be applied to a property if it defines a getter
![Screen Shot 2021-07-26 at 10 52 14 AM](https://user-images.githubusercontent.com/3625744/126936900-2a3ccd04-22dd-4339-831d-212b4026f408.png)

**Comment by gordan-glavas-codecons** [comment]
This is a Swift 5.3 compatibility issue, as of Swift 5.4 this declaration is valid. If you need this in XCode 12.4 or below, you can create a fork, remove `@ViewBuilder` from that line and add it to the label line in `init`, like this:

```swift
@ViewBuilder label: (() -> Text)?) {
```
